version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "4021:80"
  order-service:
    build: ./order-service
    ports:
      - "8011:8011"
    depends_on:
      - mongo-db
    links:
      - mongo-db
  inventory-service:
    build: ./inventory-service
    ports:
      - "8012:8012"
    depends_on:
      - mongo-db
    links:
      - mongo-db
  shipment-service:
    build: ./shipment-service
    ports:
      - "8013:8013"
    depends_on:
      - mongo-db
    links:
      - mongo-db

  mongo-db:
    container_name: mongo-db
    build: ./mongo-replset
    networks:
      - mongors-network
    ports:
      - "27021:27017"
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo2:
    container_name: mongo2
    image: mongo
    networks:
      - mongors-network
    ports:
      - "27022:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo
    networks:
      - mongors-network
    ports:
      - "27023:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo-seed-inventory-service:
    build: ./inventory-service/src/main/resources/mongo-seed
    depends_on:
      - mongo-db
    links:
      - mongo-db

networks:
  mongors-network:
    driver: bridge