version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "4021:80"
  order-service:
    build: ./order-service
    ports:
      - "8011:8011"
    depends_on:
      - mongo-db
      - kafka
    links:
      - mongo-db
      - kafka
  inventory-service:
    build: ./inventory-service
    ports:
      - "8012:8012"
    depends_on:
      - mongo-db
      - kafka
    links:
      - mongo-db
      - kafka
  shipment-service:
    build: ./shipment-service
    ports:
      - "8013:8013"
    depends_on:
      - mongo-db
      - kafka
    links:
      - mongo-db
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://192.168.1.118:9092
#      KAFKA_MESSAGE_MAX_BYTES: 2000000
    depends_on:
      - zookeeper

  mongo-db:
    container_name: mongo-db
    build: ./mongo-replset
    ports:
      - "27021:27017"
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo2:
    container_name: mongo2
    image: mongo
    ports:
      - "27022:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo
    ports:
      - "27023:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo-seed-inventory-service:
    build: ./inventory-service/src/main/resources/mongo-seed
    depends_on:
      - mongo-db
    links:
      - mongo-db